name: Request documentation for an upcoming product change
description: Request new or updated documentation for an existing Astro or Astronomer Software feature.
assignees:
  - jwitz
  - kwcanuck
labels: ["kind/enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        If you need to document a new feature, use the [new feature documentation template](https://github.com/astronomer/docs/blob/main/new-feature-template.md).
  - type: dropdown
    id: impact
    attributes:
      label: What kind of change is it? 
      multiple: false
      options:
        - New feature
        - Change to an existing feature
        - Automatic change to the data plane
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the new change
      description: Why is the new feature or functionality significant? What benefit does it provide? Why should customers care about this feature or functionality?
    validations:
      required: true
  - type: textarea
    id: relateddocs
    attributes:
      label: Provide links to existing or related source documentation here.
  - type: textarea
    id: deadline
    attributes:
      label: When is the documentation required?
      placeholder: For example, 'Q2 2023', '2/12/2023', 'Within the next month'
  - type: input
    id: reviewer
    attributes:
      label: Who should review the change?
  - type: textarea
    id: notes
    attributes:
      label: Additional notes
      description: Add additional information here that can help the docs team understand the requirements.

  