name: Request documentation for an upcoming product change
description: An upcoming change to Astro or Astronomer Software that needs documentation
assignees:
  - jwitz
  - kwcanuck
labels: ["new-feature"]
body:
  - type: dropdown
    id: impact
    attributes:
      label: What kind of change are you requesting? 
      multiple: true
      options:
        - Setup steps for an existing feature or supported configuration
        - Best practices or recommendations
        - Technical overview 
    validations:
      required: true
   - type: textarea
    id: description
    attributes:
      label: Describe the documentation you're requesting
    validations:
      required: true
  - type: textarea
    id: relateddocs
    attributes:
      label: Provide links to existing or related source documentation here.
  - type: textarea
    id: reviewers
    attributes:
      label: When is the documentation required?
      placeholder: For example, 'Q2 2023', '2/12/2023', 'Within the next month'
  - type: textarea
    id: deadline
    attributes:
      label: Who should review the change?
  - type: textarea
    id: notes
    attributes:
      label: Additional information
      description:  Add additional information here that can help the docs team understand the requirements.

  